/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mervyn.learn.gradle

import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.core.Is.`is`
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertThat(classUnderTest.greeting, `is`("Hello World!"))
    }
}
